### ISSUE TITLE
how to add options ? -o

### ISSUE THREAD

**Issue by Cyriltra** [hotio/docker-mergerfs#1]
Hi Hotio,

i'm testing your mergerfs image, but I need to add options to mergerfs:
```
-o rw,async_read=false,use_ino,allow_other,func.getattr=newest,category.action=all,category.create=ff,cache.files=partial,dropcacheonclose=true
```

i set
```
ARGS = "-o rw,async_read=false,use_ino,allow_other,func.getattr=newest,category.action=all,category.create=ff,cache.files=partial,dropcacheonclose=true"
```
and 
```
ARGS = "rw,async_read=false,use_ino,allow_other,func.getattr=newest,category.action=all,category.create=ff,cache.files=partial,dropcacheonclose=true"
```

but both failed with error: 
```
fuse: invalid argument "-o rw,async_read=false,use_ino,allow_other,func.getattr=newest,category.action=all,category.create=ff,cache.files=partial,dropcacheonclose=true"
```
or 
```
fuse: invalid argument "rw,async_read=false,use_ino,allow_other,func.getattr=newest,category.action=all,category.create=ff,cache.files=partial,dropcacheonclose=true"
```

Thanks

**Comment by hotio** [comment]
it should have worked with `-o ....`, did you try with fewer options, for example `allow_other` I'm already doing

**Comment by hotio** [comment]
How are you setting these arguments? Let me guess....compose?

**Comment by Cyriltra** [comment]
yes, i'm using docker compose.
I have set my own entrypoint, but currently facing some permissions issues to mount mountpoint. Now playing with PUID and GUID to solve it

**Comment by hotio** [comment]
your own entrypoint, means no support and your compose is probably wrong, that's why you get that error

**Comment by hotio** [comment]
also have a look at https://github.com/hotio/docker-mergerfs#using-the-mergerfs-mount-on-the-host after you fixed your compose file
