### ISSUE TITLE
Is it possible to run this on Docker for macOS

### ISSUE THREAD

**Issue by typkrft** [hotio/docker-mergerfs#2]
When I use the shared tag 

`docker run --rm --privileged --name mergerfs \
    -v /Volumes/Media\ V/Docker/MergerFS/config:/config \
    -v /Volumes/Media\ I:/source1 \
    -v /Volumes/Media\ II:/source2 \
    -v /Volumes/Media\ V/Docker/MergerFS/mount:/mountpoint:shared \
    hotio/mergerfs`

I get `path /Volumes/Media V/Docker/MergerFS/mount is mounted on /Volumes but it is not a shared mount.`

If I change or remove shared the Docker starts and I can see the files in the mountpoint through terminal but nothing is in the path on the mac Host.

**Comment by hotio** [comment]
Sorry I have 0 experience with macos, so can't help you with that.

**Comment by olvier** [comment]
Did you found a solution for your problem?

The same thing in on Synology-Devices.
The solution was
