### ISSUE TITLE
write permission denied

### ISSUE THREAD

**Issue by cola32** [hotio/docker-mergerfs#4]
Hi,
how to enable write to mount for other user?
I only can write to the merged mount with root.
Here my options:
-e ARGS="-o nonempty,rw,async_read=false,use_ino,allow_other,func.getattr=newest,category.action=all,category.create=ff,cache.files=partial,dropcacheonclose=true" \

**Comment by hotio** [comment]
See readme, ARGS is not a thing anymore...

**Comment by cola32** [comment]
There is nothing about options or anything in the readme

**Comment by hotio** [comment]
The default entrypoint is `mergerfs -f`, so you just use `docker run --rm hotio/mergerfs ...` and remove the `...` with the arguments you'd like to use, so it's the same as doing `mergerfs -f ...` on bare metal.
