### ISSUE TITLE
[Question|NO-ISSUE] how to use the slave flag

### ISSUE THREAD

**Issue by olvier** [hotio/docker-mergerfs#6]
hey,

hopefully its not the dumbest question on earth.
but searching the web didnt answer the question in detail.
do i have to use the volume-slave-flag in the container, which needs to use host-mounted-mergerfs (resilio sync, plex, nextcloud/owncloud or sth like this), or do i have to use the slave-flag in the mergerfs-container?

kinds regards

**Comment by hotio** [comment]
Let's keep the issue section for what it's meant for...You can ask generic docker questions on the discord.

**Comment by olvier** [comment]
In this context _everything_ is generic here,
but I am explicit referring to your "instruction" in your readme.

But you are right, I already had learned, that you are not willing to help anybody, referring to the other 5 "issues".

**Comment by hotio** [comment]
GitHub issues is to file actual issues with the stuff in the repository, NOT for personal support questions. Don't be a smart ass.
